CREATE TABLE ITEM (
    ITEM_ID INTEGER NOT NULL PRIMARY KEY,
    VALUE DOUBLE PRECISION DEFAULT 0,
    CATEGORY_ID INTEGER NOT NULL,
    INITIAL_DATE TIMESTAMP,
    FINAL_DATE TIMESTAMP,
    REGISTRATION_DATE DEFAULT CURRENT_DATE
);


CREATE TABLE CATEGORY (
    CATEGORY_ID INTEGER NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(25),
    CATEGORY_TYPE VARCHAR(1)
)
